#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

set -e

files=$(git diff --cached --name-only --diff-filter=ACM -- *.sol)
if [ ! -z "$files" ]; then
    forge test --silent
    npx hardhat test --parallel
fi

npm run lint
